### ISSUE TITLE
Title width fluctuation in the quote generator when generating new quotes

### ISSUE THREAD

**Issue by KeyurGK** [kelvinparmar/Quote-Generator#1]
## Issue Details :
The width of the title keeps changing whenever a new quote is generated. This affects the viewer's experience.
## Preview :
1) <img width="449" alt="image" src="https://github.com/kelvinparmar/Quote-Generator/assets/56074740/b8007550-32a3-4022-bc1d-0285f5b9ed5b">
2) <img width="630" alt="image" src="https://github.com/kelvinparmar/Quote-Generator/assets/56074740/b9644a8b-e6e4-4c45-84d5-78ec3055f8e7">

Looking forward to getting assigned to work on this.

**Comment by kelvinparmar** [comment]
Thank you @KeyurGK
